openapi: 3.0.0
info:
  title: API Lawyer
  version: '1.0'
  description: Сайт для юристов
  contact:
    name: Булатов Савелий
servers:
  - url: 'http://localhost:3000'
paths:
  /user/create:
    post:
      summary: Регистрация нового пользователя
      operationId: post-user
      tags:
        - user
      description: Регистрация пользователя в системе
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              example-1:
                value:
                  first_name: Иван
                  last_name: Петров
                  email: ivan@mail.ru
                  password: '234567'
                  user_name: Ivan
      responses:
        '200':
          description: Пользователь успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '422':
          description: Невалидные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Email уже зарегистрирован или внутренняя ошибка

  /user/authorization:
    post:
      summary: Авторизация пользователя
      operationId: post-user-authorization
      tags:
        - user
      description: Получение токена авторизации
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAuthorization'
            examples:
              example-1:
                value:
                  login: Sava
                  password: '123456'
      responses:
        '200':
          description: Успешная авторизация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '422':
          description: Невалидные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Внутренняя ошибка сервера
  /user/profile:
    get:
      summary: Получение профиля пользователя
      description: Возвращает данные профиля авторизованного пользователя
      tags:
        - user
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string
          description: Токен авторизации пользователя
      responses:
        '200':
          description: Данные профиля
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
              examples:
                example-1:
                  value:
                    user_name: Sava
                    email: sava@mail.ru
                    user_test: 5
                    first_name: Савелий
                    last_name: Булатов
        '401':
          description: Пользователь не авторизован
        '500':
          description: Ошибка сервера

  /answer:
    post:
      summary: Отправка ответов на тест
      operationId: post-answer
      tags:
        - site
      description: Отправка ответов пользователя для проверки
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string
          description: Токен авторизации
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestAnswerRequest'
            examples:
              example-1:
                value:
                  test_id: "550e8400-e29b-41d4-a716-446655440000"
                  answers:
                    - question_id: 101
                      selected_answer_ids:
                        - 3
                    - question_id: 102
                      selected_answer_ids:
                        - 5
      responses:
        '200':
          description: Результат проверки теста
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestAnswerResponse'
        '422':
          description: Ошибка в данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера
  /theories:
    get:
      summary: Получение списка теорий
      operationId: get-theories
      tags:
        - site
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string
          description: Токен авторизации
      responses:
        '200':
          description: Список теорий успешно получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Theory'
              examples:
                example-1:
                  value:
                    - id: "550e8400-e29b-41d4-a716-446655440000"
                      theory_name: Название теории
                      theory_description: Краткое описание
                      theory_full: Полный текст теории
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Внутренняя ошибка сервера
  
  /theories:
    post:
      summary: Создание новой теории
      operationId: post-theory-submit
      tags:
        - admin
      description: Добавление нового теоретического материала в базу данных
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string
          description: Токен администратора
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TheoryInput'
            examples:
              example-1:
                value:
                  theory_name: "Основы гражданского права"
                  theory_description: "Вводный курс в ГК РФ"
                  theory_full: "Полный текст теории здесь..."
      responses:
        '200':
          description: Теория успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Theory'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalError'
  
  /exemples:
    get:
      summary: Получение списка примеров
      description: 'Возвращает список примеров, связанных с теорией'
      tags:
        - site
      responses:
        '200':
          description: Список примеров получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Example'
              examples:
                example-1:
                  value:
                    - id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
                      example_name: Пример 1
                      example_description: Краткое описание
                      example_full: Полный текст примера
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Внутренняя ошибка сервера
  /examples:
    post:
      summary: Создание нового примера
      operationId: post-example-submit
      tags:
        - admin
      description: Добавление нового практического примера, связанного с теорией
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string
          description: Токен администратора
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleInput'
            examples:
              example-1:
                value:
                  example_name: "Пример решения такого-то кейса"
                  example_description: "Разбор статьи 15 ГК РФ"
                  example_full: "Здесь подробный текст примера че как и кто по итогу выйграл дело"
      responses:
        '200':
          description: Пример успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        '400':
          description: Невалидный JSON или отсутствуют поля
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка на стороне базы данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /tests:
    post:
      summary: Создание нового теста с вопросами и ответами
      operationId: post-test-submit
      tags:
        - admin
      description: Позволяет создать тест целиком, передав массив вопросов и вложенных вариантов ответов.
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string
          description: Токен администратора
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTestInput'
      responses:
        '200':
          description: Тест успешно создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Test created successfully"
        '400':
          description: Невалидный JSON или отсутствуют поля
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка на стороне базы данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /tests:
    get:
      summary: Получение списка доступных тестов
      operationId: get-tests
      tags:
        - site
      description: Возвращает краткую информацию о всех тестах (ID и название).
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string
          description: Токен авторизации
      responses:
        '200':
          description: Список тестов успешно получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestShort'
              examples:
                example-1:
                  value:
                    - id: "550e8400-e29b-41d4-a716-446655440000"
                      test_name: "Основы права"
                      created_at: "2023-10-27T10:00:00Z"
                    - id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
                      test_name: "Гражданский кодекс"
                      created_at: "2023-10-28T12:30:00Z"
        '500':
          $ref: '#/components/responses/InternalError'
  
  
  /questions:
    get:
      summary: Получение теста с вопросами
      description: Возвращает структуру теста с вопросами и вариантами ответов
      tags:
        - site
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string
          description: Токен авторизации пользователя
      responses:
        '200':
          description: Тест успешно получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestFullResponse'
              examples:
                example-1:
                  value:
                    test_id: "550e8400-e29b-41d4-a716-446655440000"
                    test_name: "Основы права"
                    questions:
                      - id: 101
                        text: "Какая отрасль права регулирует имущественные отношения?"
                        multiple: false
                        answers:
                          - id: 1
                            text: "Уголовное"
                          - id: 2
                            text: "Гражданское"
                          - id: 3
                            text: "Административное"
                      - id: 102
                        text: "Выберите источники права"
                        multiple: true
                        answers:
                          - id: 4
                            text: "Закон"
                          - id: 5
                            text: "Обычай"
                          - id: 6
                            text: "Мнение соседа"
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Внутренняя ошибка сервера
components:
  schemas:
    User:
      title: User
      type: object
      description: Данные пользователя
      properties:
        first_name:
          type: string
          description: Имя
          example: Иван
        last_name:
          type: string
          description: Фамилия
          example: Петров
        email:
          type: string
          description: Email
          format: email
          example: ivan@mail.ru
        password:
          type: string
          description: Пароль
          minLength: 6
          maxLength: 25
          example: '234567'
        user_name:
          type: string
          description: Логин
          minLength: 4
          maxLength: 20
          example: Ivan
      required:
        - first_name
        - last_name
        - email
        - password
        - user_name
    UserAuthorization:
      title: UserAuthorization
      type: object
      properties:
        login:
          type: string
          example: Sava
        password:
          type: string
          example: '123456'
      required:
        - login
        - password
    Token:
      title: Token
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
    UserProfile:
      title: UserProfile
      description: Профиль пользователя
      type: object
      properties:
        user_name:
          type: string
          example: Sava
        email:
          type: string
          example: sava@mail.ru
        user_test:
          type: integer
          example: 5
        first_name:
          type: string
          example: Савелий
        last_name:
          type: string
          example: Булатов
      required:
        - user_name
        - email
        - first_name
        - last_name
    Theory:
      title: Theory
      description: Теоретический материал
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        theory_name:
          type: string
          example: Название теории
        theory_description:
          type: string
          example: Краткое описание
        theory_full:
          type: string
          example: Полный текст теории

    TheoryInput:
      title: TheoryInput
      type: object
      required:
        - theory_name
        - theory_description
        - theory_full
      properties:
        theory_name:
          type: string
          description: Название теории
          example: "Основы гражданского права"
        theory_description:
          type: string
          description: Краткое описание
          example: "Вводный курс в ГК РФ"
        theory_full:
          type: string
          description: Полное содержание
          example: "Текст теории..."


    Example:
      title: Example
      description: 'Пример, связанный с теорией'
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
        example_name:
          type: string
          example: Пример 1
        example_description:
          type: string
          example: Краткое описание
        example_full:
          type: string
          example: Полный текст примера


    ExampleInput:
      title: ExampleInput
      type: object
      required:
        - example_name
        - example_description
        - example_full
      properties:
        example_name:
          type: string
          description: Заголовок примера
          example: "Пример решения задачи"
        example_description:
          type: string
          description: Краткое пояснение
          example: "Разбор конкретного кейса"
        example_full:
          type: string
          description: Полный текст примера
          example: "Текст примера..."
    
    TestAnswerRequest:
      title: TestAnswerRequest
      description: Ответы пользователя на тест
      type: object
      properties:
        test_id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        answers:
          type: array
          items:
            type: object
            properties:
              question_id:
                type: integer
                example: 101
              selected_answer_ids:
                type: array
                items:
                  type: integer
                example: [3, 5]
      required:
        - test_id
        - answers
    TestAnswerResponse:
      title: TestAnswerResponse
      description: Результат проверки теста
      type: object
      properties:
        test_id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        score:
          type: integer
          example: 2
      required:
        - test_id
        - score
    Error:
      title: Error
      description: Описание ошибки
      type: object
      properties:
        code:
          type: string
          example: '411'
        text:
          type: string
          example: Неправильный формат почты
      required:
        - code
        - text
    Test:
      title: Test
      description: Тест с вопросами и вариантами ответов
      type: object
      properties:
        test_id:
          type: string
          format: uuid
          description: ID теста
          example: "550e8400-e29b-41d4-a716-446655440000"
        test_name:
          type: string
          description: Название теста
          minLength: 4
          maxLength: 50
          example: Тест 1
        questions:
          type: array
          description: Список вопросов
          items:
            $ref: '#/components/schemas/Question'
      required:
        - test_id
        - test_name
        - questions

    CreateTestInput:
      title: CreateTestInput
      type: object
      required:
        - test_name
        - questions
      properties:
        test_name:
          type: string
          description: Название создаваемого теста
          example: "Итоговый тест по главе 1"
        questions:
          type: array
          description: Список вопросов к тесту
          items:
            $ref: '#/components/schemas/CreateQuestionInput'

    CreateQuestionInput:
      title: CreateQuestionInput
      type: object
      required:
        - text
        - multiple
        - answers
      properties:
        text:
          type: string
          description: Текст вопроса
          example: "В каком году была принята Конституция РФ?"
        multiple:
          type: boolean
          description: Флаг множественного выбора
          example: false
        answers:
          type: array
          description: Варианты ответов на вопрос
          items:
            $ref: '#/components/schemas/CreateAnswerInput'

    CreateAnswerInput:
      title: CreateAnswerInput
      type: object
      required:
        - text
        - is_correct
      properties:
        text:
          type: string
          description: Текст варианта ответа
          example: "1993"
        is_correct:
          type: boolean
          description: Является ли этот ответ правильным
          example: true

    Question:
      title: Question
      description: Вопрос в тесте
      type: object
      properties:
        id:
          type: integer
          description: ID вопроса
          example: 101
        text:
          type: string
          description: Текст вопроса
          minLength: 4
          maxLength: 100
          example: Сколько вам лет?
        multiple:
          type: boolean
          description: Возможен ли множественный выбор
          example: false
        answers:
          type: array
          description: Варианты ответов
          items:
            $ref: '#/components/schemas/Answer'
      required:
        - id
        - text
        - answers
    Answer:
      title: Answer
      description: Вариант ответа
      type: object
      properties:
        id:
          type: integer
          description: ID ответа
          example: 1
        text:
          type: string
          description: Текст варианта ответа
          example: '16'
      required:
        - id
        - text
tags:
  - name: user
    description: 'Методы, связанные с пользователем (регистрация, авторизция, профиль)'
  - name: site
    description: 'Основной контент сайта (теория, примеры, тесты)'